name: "(CD) (DEV)"

on:
  push:
    branches: ["dev"]
    # paths: ["**.ts", "**.tsx", "**.json"]

jobs:
  Running-On-Ubuntu:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Installing dependencies
        run: yarn install --prod

      - name: Building
        run: yarn build

      - name: Tar action
        uses: a7ul/tar-action@v1.1.2
        id: compress
        with:
          command: c
          files: |
            node_modules
            ecosystem.config.js
            package.json
            projects
            scripts
          outPath: onlytests.tarzan

      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIV_KEY }}
          source: "onlytests.tarzan"
          target: "~/"

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIV_KEY }}
          script: |
            tar -C onlytests -xf onlytests.tarzan
            cd onlytests
            pm2 stop all 2> /dev/null
            pm2 start all
